Add DOM Merge Conflict workshop
CodeYourFuture/CYF-Workshops pull request #180
Opened 2024-03-15 16:41 UTC by girdenis-p

# DOM Merge Conflicts Workshop

## Overview

This workshop is intended to be used during the Launch module. The workshop is intended to give trainees more experience with how merge conflicts arise and how to resolve them. The premise of the tasks is that, when implemented by two separate trainees, they have a high chance of creating a merge conflict.

## Previous Trial Results

This workshop was trialled by @leilafaez, @levilu800b, and @Sandra-Duarte. And I invite them to help review this pull request.

As per feedback, I have:
- Updated the README and instructions to be more clear.
- Adjusted the *conditional-rendering* task so that it is more likely that both trainees change the same line.
  - This was achieved by changing the task to ask trainees to modify the arguments of the ProfilePreview function.
- Added a new task *processing-page*.
  - This is intended to create a merge conflict when the trainees both modify logic of how the promises are processed.
  
## Side Note

This workshop may benefit from being created as a stand-alone repo similar to how previous merge conflict workshops have been. This would be purely for ease of use. I would be happy to recreate this pull request on an empty new repo if you agree to making a stand-alone repo.

2024-03-26 11:28 UTC, leilafaez approved these changes

2024-03-26 11:31 UTC, leilafaez commented
> Can someone please approve this - if you are happy with it? @leilafaez @levilu800b @Sandra-Duarte

Hi @kfklein15. I approved it but it needs 3 other reviews as well

2024-03-26 16:09 UTC, Dedekind561 requested changes
Hi @girdenis-p,
Thanks for all your effort on this workshop - some really interesting activities here! We'd like to get this in ASAP so we can start iterating on this and even use it as early as the databases module. I've suggested a few changes to simplify some of the instructions and make the tests clearer.

2024-03-26 16:28 UTC, girdenis-p commented on dom-merge-conflict/tasks/conditional-rendering/test/profilePreview.test.js
> +      profile.available = false;
Yes, it was originally intended for all properties to be passed through via a single object, but that was changed so this is legacy code that I will remove.

2024-03-26 16:34 UTC, girdenis-p commented on dom-merge-conflict/tasks/buttons-and-counter/instructions.md
> +Split the header and main content into two seperate files. Use the new functions to refactor the App function.
I intended, the trainees to end up with three files in total e.g. header.js, main.js, and app.js. I will update the instructions to reflect this in a similar manner you suggested here.

2024-03-26 16:48 UTC, girdenis-p commented on dom-merge-conflict/tasks/buttons-and-counter/instructions.md
> +Split the header and main content into two seperate files. Use the new functions to refactor the App function.
Resolved by 59f000a7608969dd26b9fb2f5aa418961c0678cc

2024-03-26 16:48 UTC, girdenis-p commented on dom-merge-conflict/tasks/buttons-and-counter/src/app.js
> +  buttonAndCounter.innerHTML = `
Resolved by 784b8edf8a50653ee46ddf28a2fb0e57ed4a1c75

2024-03-26 17:20 UTC, girdenis-p commented on dom-merge-conflict/tasks/conditional-rendering/test/profilePreview.test.js
> +    beforeEach(() => {
I have removed the beforeEach and followed your suggestion. Resolved by 476660b316e99ca77301ddfab087071b6e808fdd.

2024-03-26 17:20 UTC, girdenis-p commented on dom-merge-conflict/tasks/conditional-rendering/test/profilePreview.test.js
> +      profile.available = false;
Resolved by 476660b316e99ca77301ddfab087071b6e808fdd.

2024-03-26 17:20 UTC, girdenis-p commented on dom-merge-conflict/tasks/conditional-rendering/test/profilePreview.test.js
> +    test("contains provided image", () => {
I have merged them into one test. Resolved by 476660b316e99ca77301ddfab087071b6e808fdd.

2024-03-27 21:20 UTC, SallyMcGrath approved these changes

2024-03-27 21:20 UTC, merged