First draft feedback workshop
CodeYourFuture/CYF-Workshops pull request #230
Opened 2024-09-15 18:18 UTC by fcaroline2020

2024-09-16 11:09 UTC, SallyMcGrath submitted a review, later dismissed
I just saw you removed the review request so I stopped. Let me know when this is ready, and in the meantime mark it as draft?

Looking good so far. A bit ambitious on the amount of new information we can get through -- suggest setting some pre-work where people research the frameworks. You could set up a ChatGPT or Poe prompt for people to practise with using the different frameworks before they come to class.

Here's an example bot https://poe.com/CYF_Learn_Debugger

2024-09-16 11:09 UTC, SallyMcGrath commented on feedback/readme.md
> +Objective: Try using the Observation, Feelings, Needs and Actions (OFNA) framework to give the team member feedback. Start by discussing youor observation, how it made you feel, what the needs are an
Let's structure this so each framework is introduced clearly

### Framework OFNA
1. Define the framework and link to an external resource
2. Give a worked example of using the framework
3. Then an exercise for the learner to apply the framework to
4. Then a quiz or check for understanding so the learner can assess their work

https://docs.google.com/document/d/18LF9yn-3Hge-96ITRAQJuPZiJ71tAOSDyO3MRyBJdIc/edit?usp=sharing

2024-09-16 11:09 UTC, SallyMcGrath commented on feedback/readme.md
> +Feedback is the foundation of effective collaboration. Both giving and receiving feedback are important communication skills to master.
Excellent to see motivation here 🙏 

Let's rewrite this so it's accessible as possible to our B2 speakers. Hemingway can help here

https://hemingwayapp.com/

Aim for grade 4-6, no sentences hard or very hard to read.

2024-09-16 11:09 UTC, SallyMcGrath commented on feedback/readme.md
> +### Practice Giving Feedback
How long should they spend on each scenario? Should someone set a timer?

2024-09-16 14:21 UTC, fcaroline2020 commented
> I just saw you removed the review request so I stopped. Let me know when this is ready, and in the meantime mark it as draft?
> 
> Looking good so far. A bit ambitious on the amount of new information we can get through -- suggest setting some pre-work where people research the frameworks. You could set up a ChatGPT or Poe prompt for people to practise with using the different frameworks before they come to class.
> 
> Here's an example bot https://poe.com/CYF_Learn_Debugger

@SallyMcGrath I converted it to a draft because I wanted to discuss if this workshop makes sense to have since we already have two modules about giving/receiving feedback 
1. [[PD] Asking for feedback](https://github.com/CodeYourFuture/Module-Structuring-and-Testing-Data/issues/16) (M2 S2)
1. [[PD] Giving feedback](https://github.com/CodeYourFuture/Module-Structuring-and-Testing-Data/issues/10) (M2 S3)

My opinion is that this is giving/receiving feedback is an important topic and can never be practiced enough but I also recognize there may be other more important PD topics.

2024-11-14 17:57 UTC, kfklein15 commented on feedback/readme.md
> +The [OFNA framework](https://andyblumenthal.wordpress.com/2019/09/21/ofnr-communications-model/) consists of four parts:
Should be OFNR, not OFNA

2024-11-14 18:05 UTC, kfklein15 requested changes
This looks great. Some small changes.

2024-11-15 18:19 UTC, kfklein15 approved these changes
Changes have been made. All good to go.

2024-11-15 18:23 UTC, merged