add draft workshop for git-day-1
CodeYourFuture/CYF-Workshops pull request #80
Opened 2023-07-12 13:34 UTC by Dedekind561

Add a workshop to be completed on Git day 1.

2023-07-22 14:05 UTC, SallyMcGrath requested changes
Just a few small notes. Also some info about features you can use (waiting in PRs on curriculum)

2023-07-22 14:05 UTC, SallyMcGrath commented on git-day-1/README.md
> +where the most recent commits contain our recent work.
```suggestion
The most recent commits contain our most recent work.
```

2023-07-22 14:05 UTC, SallyMcGrath commented on git-day-1/README.md
> +To create a commit, you're going to go through the following steps:
```suggestion
Create a commit using these steps:
```

2023-07-22 14:05 UTC, SallyMcGrath commented on git-day-1/README.md
> +1. Open up your local github repo `cyf-demo-repo`.
```suggestion
1. Open up your local repo `cyf-demo-repo`.
```

It's a bit confusing to call it a local github repo

2023-07-22 14:05 UTC, SallyMcGrath commented on git-day-1/README.md
> +3. Locate `file.txt` and edit the file with the answer to the questions.
```suggestion
3. Find `file.txt` and edit the file with the answer to the questions.
```

2023-07-22 14:05 UTC, SallyMcGrath commented on git-day-1/README.md
> +> ❗ Once you've completed this **commit**, you can swap roles in your pair.
```suggestion
> ❗ Once you've completed this **commit**, swap roles in your pair.
```

2023-07-22 14:05 UTC, SallyMcGrath commented on git-day-1/README.md
> +After committing your work locally, you'll have a local branch that looks like this
```suggestion
After committing your work on your machine, you'll have a local branch that looks like this
```

2023-07-22 14:05 UTC, SallyMcGrath commented on git-day-1/README.md
> +📋 Double-check you've been committing to your branch `week-1-workshop` branch and not your `main` branch.
BTW I just updated the front end so you can use hugo note markup in comments and it will show up on the curriculum

2023-07-22 14:05 UTC, SallyMcGrath commented on git-day-1/README.md
> +In other words, we've not added our local branch on to the remote fork on Github.
```suggestion
In other words, we have _not_ added our local branch on to the remote fork on Github.
```

Avoid strong regionalisms like we've not

2023-07-25 07:59 UTC, Dedekind561 commented on git-day-1/README.md
> +In this workshop, you'll learn the following:
I've put these learning objectives into front matter - but they're not being rendered

2023-07-25 10:26 UTC, SallyMcGrath commented on git-day-1/README.md
> +In this workshop, you'll learn the following:
```objectives
- [ ] like this
```

2023-07-25 10:27 UTC, SallyMcGrath commented on git-day-1/README.md
> +In this workshop, you'll learn the following:
er. ```objectives

2023-07-26 19:19 UTC, merged

2023-07-29 10:48 UTC, 40thieves commented on git-day-1/README.md
> +Now clone your forked repository from Github onto your local machine.
Sorry for being late to the party but I'm struggling to make sense of this exercise. I'm happy to submit a PR with fixes but I wanted to understand the intention first.

> Get a local copy of a repository on your local machine.

"Get" is a bit ambiguous here: does this mean to open an existing repo? Or to clone a repo?

If it's the latter, which repo should they clone? Any repo? I think I would prefer a specific repo, as it'll just slow down the exercise to pick a repo to clone.

> Now clone your forked repository from Github onto your local machine.

Assuming the points above are to clone a forked repo, this is just repeating the same point?

Or is this line just in the wrong place - should it be above the list?